# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b14f669e1f04530881e538c03fef76eee744cd089ce6e145eea4489da5fcbd3ab1383a1ae8c987576a602bb229f928f5625c4a935b8802ccca8472966146cb4

test:
  secret_key_base: 80fc0638f6a95c4861bb67c3737f9197d5889a5ee6bf7dd9cb779c0efe10550e29d2f572d27b15b4515e3a2119f7b846dc77e1716553240aec03e33bbed3d495

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
